#!/bin/bash

JAVA=java
if [ -n "$JAVA_HOME" ]; then
	JAVA=$JAVA_HOME/bin/java
fi

if [ ! -n "$MONKEYSCRIPT_HOME" ]; then
	export MONKEYSCRIPT_HOME=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
fi

$JAVA -Xbootclasspath/p:"$MONKEYSCRIPT_HOME/js.jar" -jar $MONKEYSCRIPT_HOME/monkeyscript.jar "$@"

